import { GoogleGenAI, Type } from "@google/genai";
import { DetectionResult, HumanizeResult } from "../types";

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

const MODEL_NAME = 'gemini-2.5-flash';

export const detectAIContent = async (text: string): Promise<DetectionResult> => {
  try {
    const prompt = `
      Analyze the following text to determine if it was likely generated by an AI model or written by a human.
      Focus on sentence structure variety, perplexity, burstiness, and common AI phrases.
      
      Determine a probability score (0-100) where 0 is definitely Human and 100 is definitely AI.
      Determine a confidence score (0-100) representing how sure you are of this assessment.

      Assign a label based on the probability score:
      - 0-20: "Very Likely Human"
      - 21-40: "Likely Human"
      - 41-60: "Unclear / Mixed Signals"
      - 61-80: "Likely AI"
      - 81-100: "Very Likely AI"
      
      Extract exact sentences from the text that appear most artificial or AI-generated. Return them as a list of strings.
      If no specific sentences stand out (e.g. text is human), return an empty list.

      Text to analyze:
      "${text}"
    `;

    const response = await ai.models.generateContent({
      model: MODEL_NAME,
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            score: {
              type: Type.NUMBER,
              description: "A score from 0 to 100 indicating the likelihood of being AI-generated.",
            },
            confidence: {
              type: Type.NUMBER,
              description: "A score from 0 to 100 indicating the model's confidence in its prediction.",
            },
            label: {
              type: Type.STRING,
              description: "The classification label (e.g., 'Very Likely AI', 'Likely Human').",
            },
            analysis: {
              type: Type.STRING,
              description: "A concise paragraph explaining why this score was given, citing specific patterns found or missing.",
            },
            highlightedSentences: {
              type: Type.ARRAY,
              items: { type: Type.STRING },
              description: "Exact sentences from the input text that strongly indicate AI generation.",
            }
          },
          required: ["score", "confidence", "label", "analysis", "highlightedSentences"],
        },
      },
    });

    if (!response.text) {
      throw new Error("No response from AI");
    }

    const result = JSON.parse(response.text);
    return result as DetectionResult;

  } catch (error) {
    console.error("Error detecting AI content:", error);
    throw error;
  }
};

export const humanizeContent = async (text: string): Promise<HumanizeResult> => {
  try {
    const prompt = `
      Rewrite the following text to make it sound more natural, human, and engaging. 
      Vary sentence lengths, use idioms where appropriate, and remove robotic or repetitive phrasing. 
      Keep the original meaning but improve the flow and tone.
      
      Original Text:
      "${text}"
    `;

    const response = await ai.models.generateContent({
      model: MODEL_NAME,
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            humanizedText: {
              type: Type.STRING,
              description: "The rewritten text.",
            },
            changesSummary: {
              type: Type.STRING,
              description: "A brief summary of what changes were made to make it sound more human.",
            },
          },
          required: ["humanizedText", "changesSummary"],
        },
      },
    });

    if (!response.text) {
      throw new Error("No response from AI");
    }

    const result = JSON.parse(response.text);
    return {
      originalText: text,
      humanizedText: result.humanizedText,
      changesSummary: result.changesSummary,
    };

  } catch (error) {
    console.error("Error humanizing content:", error);
    throw error;
  }
};