import { GoogleGenAI, Type } from "@google/genai";
import { DetectionResult, HumanizeResult, AppSettings } from "../types";

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

const DEFAULT_SETTINGS: AppSettings = {
  model: 'gemini-2.5-flash',
  temperature: 0.3,
  maxTokens: 1000,
  enableHistory: true,
};

export const detectAIContent = async (text: string, settings: Partial<AppSettings> = {}): Promise<DetectionResult> => {
  const mergedSettings = { ...DEFAULT_SETTINGS, ...settings };
  try {
    const prompt = `
      Analyze the following text to determine if it was likely generated by an AI model or written by a human.
      Focus on sentence structure variety, perplexity, burstiness, and common AI phrases.
      
      Text to analyze:
      "${text}"
    `;

    const response = await ai.models.generateContent({
      model: mergedSettings.model,
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            score: {
              type: Type.NUMBER,
              description: "A score from 0 to 100 indicating the likelihood of being AI-generated. 100 is definitely AI, 0 is definitely Human.",
            },
            label: {
              type: Type.STRING,
              description: "A short label like 'Highly Likely AI', 'Mixed Signals', 'Likely Human'.",
            },
            analysis: {
              type: Type.STRING,
              description: "A concise paragraph explaining why this score was given, citing specific patterns found or missing.",
            },
          },
          required: ["score", "label", "analysis"],
        },
        generationConfig: {
          temperature: mergedSettings.temperature,
          maxOutputTokens: mergedSettings.maxTokens,
        }
      },
    });

    if (!response.text) {
      throw new Error("No response from AI");
    }

    const result = JSON.parse(response.text);
    return result as DetectionResult;

  } catch (error) {
    console.error("Error detecting AI content:", error);
    throw error;
  }
};

export const humanizeContent = async (text: string, settings: Partial<AppSettings> = {}): Promise<HumanizeResult> => {
  const mergedSettings = { ...DEFAULT_SETTINGS, ...settings };
  try {
    const prompt = `
      Rewrite the following text to make it sound more natural, human, and engaging. 
      Vary sentence lengths, use idioms where appropriate, and remove robotic or repetitive phrasing. 
      Keep the original meaning but improve the flow and tone.
      
      Original Text:
      "${text}"
    `;

    const response = await ai.models.generateContent({
      model: mergedSettings.model,
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            humanizedText: {
              type: Type.STRING,
              description: "The rewritten text.",
            },
            changesSummary: {
              type: Type.STRING,
              description: "A brief summary of what changes were made to make it sound more human.",
            },
          },
          required: ["humanizedText", "changesSummary"],
        },
        generationConfig: {
          temperature: mergedSettings.temperature,
          maxOutputTokens: mergedSettings.maxTokens,
        }
      },
    });

    if (!response.text) {
      throw new Error("No response from AI");
    }

    const result = JSON.parse(response.text);
    return {
      originalText: text,
      humanizedText: result.humanizedText,
      changesSummary: result.changesSummary,
    };

  } catch (error) {
    console.error("Error humanizing content:", error);
    throw error;
  }
};
